### ISSUE TITLE
Bug - IKEA Styrbar / Jetström Down button long press doesn't release | left/right buttons don't work

### ISSUE THREAD

**Issue by Seminko** [EPMatt/awesome-ha-blueprints#949]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2025.10.4

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Set up Hook - Light with Controller - IKEA E2001/E2002 STYRBAR Remote control and it mostly works.
When I do Up button long press it increases brightness correctly and when I release it, it stops. Great
However, when I long press the down button and release it immediately when the brightness starts to decrease it doesn't stop and decreases brightness until the light is completely off.

Also, the left and right buttons don't work (I left them at default which should change temperature? as per:

> (Optional) Light color mode
> Specify how the controller will set the light color. Choose "Color Temperature" and "Hue - Saturation" depending on the features supported by your light. If you are not sure you can select "Auto". "None" will disable color control features.

I tried If I could set it up myself but apparently I cannot find temperature control under the device (IKEA Jetström), yet when I bring up the native HA light interface I can change the temperature so it can be done.

I tried changing the light color mode in Hook - Light from auto to temperature but that did nothing.

### Automation YAML config

```yaml
alias: Controller - IKEA E2001/E2002 STYRBAR Remote control
description: ""
use_blueprint:
  path: lsismeiro/ikea_e2001_e2002.yaml
  input:
    integration: ZHA
    controller_device: 46e870a32d42baac192e18bfc429d3a9
    helper_last_controller_event: input_text.ikea_jetstrom_blueprint_helper


alias: Hook - Light - test
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_device: 46e870a32d42baac192e18bfc429d3a9
    controller_model: IKEA E2001/E2002 STYRBAR Remote control
    light: light.ikea_jetstrom_6060_light
    light_color_mode: Color Temperature
    force_brightness: true
    on_brightness: 255
```

### To Reproduce

n/a

### Expected behavior

n/a

### Actual Behaviour

n/a

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by Seminko** [comment]
> What firmware version of the styrbar?

0x02040005

**Comment by yarafie** [comment]
@Seminko 

Can you give this a try.
I think I fixed the logic issue in the blueprint.

Redownload the blueprint again and re-setup your automation as I moved a few things around, mainly the order of the inputs Up, Down, Right, Left. That really shouldn't affect anything, but better to start clean.

https://yarafie.github.io/awesome-ha-blueprints/blueprints/controllers/ikea_e2001_e2002?version=latest

**Comment by Seminko** [comment]
> [@Seminko](https://github.com/Seminko)
> 
> Can you give this a try. I think I fixed the logic issue in the blueprint.
> 
> Redownload the blueprint again and re-setup your automation as I moved a few things around, mainly the order of the inputs Up, Down, Right, Left. That really shouldn't affect anything, but better to start clean.
> 
> https://yarafie.github.io/awesome-ha-blueprints/blueprints/controllers/ikea_e2001_e2002?version=latest

Removed both the light and the controller, set them both up again but sorry to report both issues are still present.

**Comment by thamrx** [comment]
I’m experiencing the same issue with [ikea_e2201](https://github.com/EPMatt/awesome-ha-blueprints/tree/main/blueprints/controllers/ikea_e2201)￼: the down button keeps dimming continuously.

**Comment by Seminko** [comment]
> I’m experiencing the same issue with [ikea_e2123](https://github.com/EPMatt/awesome-ha-blueprints/tree/main/blueprints/controllers/ikea_e2123)￼: the down button keeps dimming continuously.

Good to hear it's not a "me problem".

**Comment by yarafie** [comment]
@thamrx @Seminko 

I confirm it's not a you problem it's a me problem  :)

I have a logic issue in the blueprint for the long presses, which has given me a headache to wrap my head around it. So had to take a break so I could look at it fresh.

The same logic is used in the Symfonisk ikea_2123 , so if I fix it for the Styrbar ikea_e2001_e2002, I'll be able to fix it for all other blueprints which uses the same long press logic.

Sorry about that.

**Comment by yarafie** [comment]
@thamrx @Seminko 

My apologies for taking so long, but I had to rethink the whole approach.

I managed to fix it and have succesfully tested it using both custom actions and the Light Hook.

I had to re-introduce the external text helper, helper_last_controller_event, so you will have to first create a text helper in Home Assistant, and when setting up your automation from the blueprint again make sure you select it.

You can read about text helpers here:
https://yarafie.github.io/awesome-ha-blueprints/docs/controllers-hooks-ecosystem#helper---last-controller-event-input

Redownload the blueprint from here:
https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2001_e2002

**Comment by Seminko** [comment]
@yarafie - just tested, I have good news and bad news :-D

Good news:
- the down long press is fixed
- not sure if I'm imagining things but the left and right short press works better

Bad news:
- the up, left and right long press doesn't work for me at all
- the left and right short press have a strange quirk - not sure what dictates the temperature "checkpoints" (ie the temperature jumps) but for each press it jumps pretty significantly (which is fine) but the last (or first) press jumps the temp by only a smidge, only cca 80K, maybe not even that.

**Comment by yarafie** [comment]
@Seminko 

You are going to have to tune 3 numbers for your environment, debounce, long and double press delays.

Try increasing the long_press_delay from the default of 250 by +25 and try again until you get it to work for up long presses.

For left and right, at least for me, the initial long press takes a while to register with the styrbar i'm using.
Going to try with another styrbar to see if it might be a problem with device itself.

For me I had to change the double_press_delay from 250 to 400 to get double presses to work.

**Comment by yarafie** [comment]
> I’m experiencing the same issue with [ikea_e2201](https://github.com/EPMatt/awesome-ha-blueprints/tree/main/blueprints/controllers/ikea_e2201)￼: the down button keeps dimming continuously.

@thamrx 

ZHA or Zigbee2MQTT?
Did you try increasing/decreasing helper_long_press_delay from the default 250? Try +/- 25 increments.
Can you capture the events when you push and hold the down button and then release?

**Comment by yarafie** [comment]
> > I’m experiencing the same issue with [ikea_e2201](https://github.com/EPMatt/awesome-ha-blueprints/tree/main/blueprints/controllers/ikea_e2201)￼: the down button keeps dimming continuously.
> 
> [@thamrx](https://github.com/thamrx)
> 
> ZHA or Zigbee2MQTT? Did you try increasing/decreasing helper_long_press_delay from the default 250? Try +/- 25 increments. Can you capture the events when you push and hold the down button and then release?

@thamrx 

I just went through testing it with my Rodret. 

I set it up using Custom Actions and long press and double press works I did have to set my double press delay to 400 from the default 250.
I also set it up using the light hook and long press for both up/down work for me the stop brightness Up/Down when I release the buttons.

So not sure why yours is not working.
Note I'm using zigbee2mqtt so not sure if your issue is ZHA related.

**Comment by Seminko** [comment]
> [@Seminko](https://github.com/Seminko)
> 
> You are going to have to tune 3 numbers for your environment, debounce, long and double press delays.
> 
> Try increasing the long_press_delay from the default of 250 by +25 and try again until you get it to work for up long presses.

@yarafie Logically, this doesn't make sense. If my down button long press works correctly, the up button should too since there is only a single non-button-specific option for long press delay.

**Comment by yarafie** [comment]
> > [@Seminko](https://github.com/Seminko)
> > You are going to have to tune 3 numbers for your environment, debounce, long and double press delays.
> > Try increasing the long_press_delay from the default of 250 by +25 and try again until you get it to work for up long presses.
> 
> [@yarafie](https://github.com/yarafie) Logically, this doesn't make sense. If my down button long press works correctly, the up button should too since there is only a single non-button-specific option for long press delay.

Since you are using ZHA,
Can you send me the exact events that are triggered when you do a long press up and long press down and also the events when you release each.

Regarding "Logically", I understand, the reason that the long_press_delay setting was put in was due to potential timing issues as these devuces are a bit finiky,

**Comment by Seminko** [comment]
> Since you are using ZHA, Can you send me the exact events that are triggered when you do a long press up and long press down and also the events when you release each.

Yep there's definitely something going on. The up button long press doesn't fire almost anything compared to the down button...

<details>
  <summary>UP BUTTON LONG PRESS (held for at least 5 seconds)</summary>

```
event_type: zha_event
data:
  device_ieee: f8:44:77:ff:fe:75:e2:65
  device_id: 46e870a32d42baac192e18bfc429d3a9
  unique_id: f8:44:77:ff:fe:75:e2:65:1:0x0008
  endpoint_id: 1
  cluster_id: 8
  command: move_with_on_off
  args:
    - 0
    - 83
  params:
    move_mode: 0
    rate: 83
origin: LOCAL
time_fired: "2025-11-16T10:28:15.694480+00:00"
context:
  id: 01KA63AM6EM7JD0FEJ190KVTE8
  parent_id: null
  user_id: null

event_type: zha_event
data:
  device_ieee: f8:44:77:ff:fe:75:e2:65
  device_id: 46e870a32d42baac192e18bfc429d3a9
  unique_id: f8:44:77:ff:fe:75:e2:65:1:0x0008
  endpoint_id: 1
  cluster_id: 8
  command: stop_with_on_off
  args: []
  params: {}
origin: LOCAL
time_fired: "2025-11-16T10:28:18.477745+00:00"
context:
  id: 01KA63APXD7PYZSVE8D4ABH4QM
  parent_id: null
  user_id: null
```
</details>

<details>
  <summary>DOWN BUTTON LONG PRESS</summary>

```
event_type: state_changed
data:
  entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
  old_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1762973505391"
      last_triggered: "2025-11-16T10:26:57.877885+00:00"
      mode: restart
      current: 0
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T08:05:12.592505+00:00"
    last_reported: "2025-11-16T10:26:58.356730+00:00"
    last_updated: "2025-11-16T10:26:58.356730+00:00"
    context:
      id: 01KA63886C48V343DXQ37HX0XC
      parent_id: 01KA638865S6PKDA9PRETH87M2
      user_id: null
  new_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1762973505391"
      last_triggered: "2025-11-16T10:29:17.236900+00:00"
      mode: restart
      current: 1
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T08:05:12.592505+00:00"
    last_reported: "2025-11-16T10:29:17.237090+00:00"
    last_updated: "2025-11-16T10:29:17.237090+00:00"
    context:
      id: 01KA63CG942K5V5RNR13Z1PCQ9
      parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:17.237090+00:00"
context:
  id: 01KA63CG942K5V5RNR13Z1PCQ9
  parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
  user_id: null

event_type: call_service
data:
  domain: input_text
  service: set_value
  service_data:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    value:
      a: button-down-long
      t: 1763288957.659639
origin: LOCAL
time_fired: "2025-11-16T10:29:17.661439+00:00"
context:
  id: 01KA63CG942K5V5RNR13Z1PCQ9
  parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
  user_id: null

event_type: state_changed
data:
  entity_id: input_text.ikea_jetstrom_blueprint_helper
  old_state:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    state: "{\"a\":\"button-down-release\",\"t\":1763288818.349646}"
    attributes:
      editable: true
      min: 0
      max: 100
      pattern: null
      mode: text
      icon: mdi:ceiling-light
      friendly_name: IKEA Jetström blueprint helper
    last_changed: "2025-11-16T10:26:58.351006+00:00"
    last_reported: "2025-11-16T10:26:58.351006+00:00"
    last_updated: "2025-11-16T10:26:58.351006+00:00"
    context:
      id: 01KA63886C48V343DXQ37HX0XC
      parent_id: 01KA638865S6PKDA9PRETH87M2
      user_id: null
  new_state:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    state: "{\"a\":\"button-down-long\",\"t\":1763288957.659639}"
    attributes:
      editable: true
      min: 0
      max: 100
      pattern: null
      mode: text
      icon: mdi:ceiling-light
      friendly_name: IKEA Jetström blueprint helper
    last_changed: "2025-11-16T10:29:17.662719+00:00"
    last_reported: "2025-11-16T10:29:17.662719+00:00"
    last_updated: "2025-11-16T10:29:17.662719+00:00"
    context:
      id: 01KA63CG942K5V5RNR13Z1PCQ9
      parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:17.662719+00:00"
context:
  id: 01KA63CG942K5V5RNR13Z1PCQ9
  parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
  user_id: null

event_type: ahb_controller_event
data:
  controller: 46e870a32d42baac192e18bfc429d3a9
  action: button_down_long
origin: LOCAL
time_fired: "2025-11-16T10:29:17.714110+00:00"
context:
  id: 01KA63CG942K5V5RNR13Z1PCQ9
  parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
  user_id: null

event_type: state_changed
data:
  entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
  old_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1762973505391"
      last_triggered: "2025-11-16T10:29:17.236900+00:00"
      mode: restart
      current: 1
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T08:05:12.592505+00:00"
    last_reported: "2025-11-16T10:29:17.237090+00:00"
    last_updated: "2025-11-16T10:29:17.237090+00:00"
    context:
      id: 01KA63CG942K5V5RNR13Z1PCQ9
      parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
      user_id: null
  new_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1762973505391"
      last_triggered: "2025-11-16T10:29:17.236900+00:00"
      mode: restart
      current: 0
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T08:05:12.592505+00:00"
    last_reported: "2025-11-16T10:29:17.726950+00:00"
    last_updated: "2025-11-16T10:29:17.726950+00:00"
    context:
      id: 01KA63CG942K5V5RNR13Z1PCQ9
      parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:17.726950+00:00"
context:
  id: 01KA63CG942K5V5RNR13Z1PCQ9
  parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
  user_id: null

event_type: automation_triggered
data:
  name: Hook - Light
  entity_id: automation.hook_light
  source: event 'ahb_controller_event'
origin: LOCAL
time_fired: "2025-11-16T10:29:17.742961+00:00"
context:
  id: 01KA63CGS04PD2XX55VDEGDDWV
  parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
  user_id: null

event_type: state_changed
data:
  entity_id: light.ikea_jetstrom_6060_light
  old_state:
    entity_id: light.ikea_jetstrom_6060_light
    state: "on"
    attributes:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 3322
      color_temp: 301
      hs_color:
        - 27.369
        - 48.786
      rgb_color:
        - 255
        - 187
        - 131
      xy_color:
        - 0.467
        - 0.377
      off_with_transition: false
      off_brightness: null
      friendly_name: IKEA JETSTROM 6060 Light
      supported_features: 40
    last_changed: "2025-11-16T10:26:49.458894+00:00"
    last_reported: "2025-11-16T10:29:09.751928+00:00"
    last_updated: "2025-11-16T10:29:09.750309+00:00"
    context:
      id: 01KA63C8TS7GBACZSDXN4WS7ZB
      parent_id: null
      user_id: 19d971771cde4409b3a751a027187276
  new_state:
    entity_id: light.ikea_jetstrom_6060_light
    state: "on"
    attributes:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 228
      color_temp_kelvin: 3322
      color_temp: 301
      hs_color:
        - 27.369
        - 48.786
      rgb_color:
        - 255
        - 187
        - 131
      xy_color:
        - 0.467
        - 0.377
      off_with_transition: false
      off_brightness: null
      friendly_name: IKEA JETSTROM 6060 Light
      supported_features: 40
    last_changed: "2025-11-16T10:26:49.458894+00:00"
    last_reported: "2025-11-16T10:29:17.911858+00:00"
    last_updated: "2025-11-16T10:29:17.911858+00:00"
    context:
      id: 01KA63CGS04PD2XX55VDEGDDWV
      parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:17.911858+00:00"
context:
  id: 01KA63CGS04PD2XX55VDEGDDWV
  parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
  user_id: null

event_type: call_service
data:
  domain: light
  service: turn_on
  service_data:
    brightness: 202.6
    transition: 0.25
    entity_id: light.ikea_jetstrom_6060_light
origin: LOCAL
time_fired: "2025-11-16T10:29:18.197991+00:00"
context:
  id: 01KA63CGS04PD2XX55VDEGDDWV
  parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
  user_id: null

event_type: state_changed
data:
  entity_id: light.ikea_jetstrom_6060_light
  old_state:
    entity_id: light.ikea_jetstrom_6060_light
    state: "on"
    attributes:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 228
      color_temp_kelvin: 3322
      color_temp: 301
      hs_color:
        - 27.369
        - 48.786
      rgb_color:
        - 255
        - 187
        - 131
      xy_color:
        - 0.467
        - 0.377
      off_with_transition: false
      off_brightness: null
      friendly_name: IKEA JETSTROM 6060 Light
      supported_features: 40
    last_changed: "2025-11-16T10:26:49.458894+00:00"
    last_reported: "2025-11-16T10:29:17.911858+00:00"
    last_updated: "2025-11-16T10:29:17.911858+00:00"
    context:
      id: 01KA63CGS04PD2XX55VDEGDDWV
      parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
      user_id: null
  new_state:
    entity_id: light.ikea_jetstrom_6060_light
    state: "on"
    attributes:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 202
      color_temp_kelvin: 3322
      color_temp: 301
      hs_color:
        - 27.369
        - 48.786
      rgb_color:
        - 255
        - 187
        - 131
      xy_color:
        - 0.467
        - 0.377
      off_with_transition: false
      off_brightness: null
      friendly_name: IKEA JETSTROM 6060 Light
      supported_features: 40
    last_changed: "2025-11-16T10:26:49.458894+00:00"
    last_reported: "2025-11-16T10:29:18.328506+00:00"
    last_updated: "2025-11-16T10:29:18.328506+00:00"
    context:
      id: 01KA63CGS04PD2XX55VDEGDDWV
      parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:18.328506+00:00"
context:
  id: 01KA63CGS04PD2XX55VDEGDDWV
  parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
  user_id: null

event_type: call_service
data:
  domain: light
  service: turn_on
  service_data:
    brightness: 176.6
    transition: 0.25
    entity_id: light.ikea_jetstrom_6060_light
origin: LOCAL
time_fired: "2025-11-16T10:29:18.620111+00:00"
context:
  id: 01KA63CGS04PD2XX55VDEGDDWV
  parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
  user_id: null

event_type: state_changed
data:
  entity_id: light.ikea_jetstrom_6060_light
  old_state:
    entity_id: light.ikea_jetstrom_6060_light
    state: "on"
    attributes:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 202
      color_temp_kelvin: 3322
      color_temp: 301
      hs_color:
        - 27.369
        - 48.786
      rgb_color:
        - 255
        - 187
        - 131
      xy_color:
        - 0.467
        - 0.377
      off_with_transition: false
      off_brightness: null
      friendly_name: IKEA JETSTROM 6060 Light
      supported_features: 40
    last_changed: "2025-11-16T10:26:49.458894+00:00"
    last_reported: "2025-11-16T10:29:18.328506+00:00"
    last_updated: "2025-11-16T10:29:18.328506+00:00"
    context:
      id: 01KA63CGS04PD2XX55VDEGDDWV
      parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
      user_id: null
  new_state:
    entity_id: light.ikea_jetstrom_6060_light
    state: "on"
    attributes:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 176
      color_temp_kelvin: 3322
      color_temp: 301
      hs_color:
        - 27.369
        - 48.786
      rgb_color:
        - 255
        - 187
        - 131
      xy_color:
        - 0.467
        - 0.377
      off_with_transition: false
      off_brightness: null
      friendly_name: IKEA JETSTROM 6060 Light
      supported_features: 40
    last_changed: "2025-11-16T10:26:49.458894+00:00"
    last_reported: "2025-11-16T10:29:18.745233+00:00"
    last_updated: "2025-11-16T10:29:18.745233+00:00"
    context:
      id: 01KA63CGS04PD2XX55VDEGDDWV
      parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:18.745233+00:00"
context:
  id: 01KA63CGS04PD2XX55VDEGDDWV
  parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
  user_id: null

event_type: zha_event
data:
  device_ieee: f8:44:77:ff:fe:75:e2:65
  device_id: 46e870a32d42baac192e18bfc429d3a9
  unique_id: f8:44:77:ff:fe:75:e2:65:1:0x0008
  endpoint_id: 1
  cluster_id: 8
  command: stop
  args:
    - 0
    - 0
  params:
    options_mask: 0
    options_override: 0
origin: LOCAL
time_fired: "2025-11-16T10:29:18.788455+00:00"
context:
  id: 01KA63CHT48K0A3C71NJG8792A
  parent_id: null
  user_id: null

event_type: automation_triggered
data:
  name: Controller - IKEA E2001/E2002 STYRBAR Remote control
  entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
  source: event 'zha_event'
origin: LOCAL
time_fired: "2025-11-16T10:29:18.815303+00:00"
context:
  id: 01KA63CHTFB42QF5YVEM01RF6N
  parent_id: 01KA63CHT48K0A3C71NJG8792A
  user_id: null

event_type: state_changed
data:
  entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
  old_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1762973505391"
      last_triggered: "2025-11-16T10:29:17.236900+00:00"
      mode: restart
      current: 0
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T08:05:12.592505+00:00"
    last_reported: "2025-11-16T10:29:17.726950+00:00"
    last_updated: "2025-11-16T10:29:17.726950+00:00"
    context:
      id: 01KA63CG942K5V5RNR13Z1PCQ9
      parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
      user_id: null
  new_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1762973505391"
      last_triggered: "2025-11-16T10:29:18.815750+00:00"
      mode: restart
      current: 1
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T08:05:12.592505+00:00"
    last_reported: "2025-11-16T10:29:18.815928+00:00"
    last_updated: "2025-11-16T10:29:18.815928+00:00"
    context:
      id: 01KA63CHTFB42QF5YVEM01RF6N
      parent_id: 01KA63CHT48K0A3C71NJG8792A
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:18.815928+00:00"
context:
  id: 01KA63CHTFB42QF5YVEM01RF6N
  parent_id: 01KA63CHT48K0A3C71NJG8792A
  user_id: null

event_type: call_service
data:
  domain: light
  service: turn_on
  service_data:
    brightness: 150.6
    transition: 0.25
    entity_id: light.ikea_jetstrom_6060_light
origin: LOCAL
time_fired: "2025-11-16T10:29:19.048964+00:00"
context:
  id: 01KA63CGS04PD2XX55VDEGDDWV
  parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
  user_id: null

event_type: call_service
data:
  domain: input_text
  service: set_value
  service_data:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    value:
      a: button-down-release
      t: 1763288959.238488
origin: LOCAL
time_fired: "2025-11-16T10:29:19.240360+00:00"
context:
  id: 01KA63CHTFB42QF5YVEM01RF6N
  parent_id: 01KA63CHT48K0A3C71NJG8792A
  user_id: null

event_type: state_changed
data:
  entity_id: input_text.ikea_jetstrom_blueprint_helper
  old_state:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    state: "{\"a\":\"button-down-long\",\"t\":1763288957.659639}"
    attributes:
      editable: true
      min: 0
      max: 100
      pattern: null
      mode: text
      icon: mdi:ceiling-light
      friendly_name: IKEA Jetström blueprint helper
    last_changed: "2025-11-16T10:29:17.662719+00:00"
    last_reported: "2025-11-16T10:29:17.662719+00:00"
    last_updated: "2025-11-16T10:29:17.662719+00:00"
    context:
      id: 01KA63CG942K5V5RNR13Z1PCQ9
      parent_id: 01KA63CG8RN7BV8MS1ZQZSGVTX
      user_id: null
  new_state:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    state: "{\"a\":\"button-down-release\",\"t\":1763288959.238488}"
    attributes:
      editable: true
      min: 0
      max: 100
      pattern: null
      mode: text
      icon: mdi:ceiling-light
      friendly_name: IKEA Jetström blueprint helper
    last_changed: "2025-11-16T10:29:19.241544+00:00"
    last_reported: "2025-11-16T10:29:19.241544+00:00"
    last_updated: "2025-11-16T10:29:19.241544+00:00"
    context:
      id: 01KA63CHTFB42QF5YVEM01RF6N
      parent_id: 01KA63CHT48K0A3C71NJG8792A
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:19.241544+00:00"
context:
  id: 01KA63CHTFB42QF5YVEM01RF6N
  parent_id: 01KA63CHT48K0A3C71NJG8792A
  user_id: null

event_type: ahb_controller_event
data:
  controller: 46e870a32d42baac192e18bfc429d3a9
  action: button_down_release
origin: LOCAL
time_fired: "2025-11-16T10:29:19.287479+00:00"
context:
  id: 01KA63CHTFB42QF5YVEM01RF6N
  parent_id: 01KA63CHT48K0A3C71NJG8792A
  user_id: null

event_type: call_service
data:
  domain: input_text
  service: set_value
  service_data:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    value:
      a: button-down-release
      t: 1763288959.291924
origin: LOCAL
time_fired: "2025-11-16T10:29:19.292925+00:00"
context:
  id: 01KA63CHTFB42QF5YVEM01RF6N
  parent_id: 01KA63CHT48K0A3C71NJG8792A
  user_id: null

event_type: state_changed
data:
  entity_id: input_text.ikea_jetstrom_blueprint_helper
  old_state:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    state: "{\"a\":\"button-down-release\",\"t\":1763288959.238488}"
    attributes:
      editable: true
      min: 0
      max: 100
      pattern: null
      mode: text
      icon: mdi:ceiling-light
      friendly_name: IKEA Jetström blueprint helper
    last_changed: "2025-11-16T10:29:19.241544+00:00"
    last_reported: "2025-11-16T10:29:19.241544+00:00"
    last_updated: "2025-11-16T10:29:19.241544+00:00"
    context:
      id: 01KA63CHTFB42QF5YVEM01RF6N
      parent_id: 01KA63CHT48K0A3C71NJG8792A
      user_id: null
  new_state:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    state: "{\"a\":\"button-down-release\",\"t\":1763288959.291924}"
    attributes:
      editable: true
      min: 0
      max: 100
      pattern: null
      mode: text
      icon: mdi:ceiling-light
      friendly_name: IKEA Jetström blueprint helper
    last_changed: "2025-11-16T10:29:19.307986+00:00"
    last_reported: "2025-11-16T10:29:19.307986+00:00"
    last_updated: "2025-11-16T10:29:19.307986+00:00"
    context:
      id: 01KA63CHTFB42QF5YVEM01RF6N
      parent_id: 01KA63CHT48K0A3C71NJG8792A
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:19.307986+00:00"
context:
  id: 01KA63CHTFB42QF5YVEM01RF6N
  parent_id: 01KA63CHT48K0A3C71NJG8792A
  user_id: null

event_type: state_changed
data:
  entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
  old_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1762973505391"
      last_triggered: "2025-11-16T10:29:18.815750+00:00"
      mode: restart
      current: 1
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T08:05:12.592505+00:00"
    last_reported: "2025-11-16T10:29:18.815928+00:00"
    last_updated: "2025-11-16T10:29:18.815928+00:00"
    context:
      id: 01KA63CHTFB42QF5YVEM01RF6N
      parent_id: 01KA63CHT48K0A3C71NJG8792A
      user_id: null
  new_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1762973505391"
      last_triggered: "2025-11-16T10:29:18.815750+00:00"
      mode: restart
      current: 0
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T08:05:12.592505+00:00"
    last_reported: "2025-11-16T10:29:19.309731+00:00"
    last_updated: "2025-11-16T10:29:19.309731+00:00"
    context:
      id: 01KA63CHTFB42QF5YVEM01RF6N
      parent_id: 01KA63CHT48K0A3C71NJG8792A
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:19.309731+00:00"
context:
  id: 01KA63CHTFB42QF5YVEM01RF6N
  parent_id: 01KA63CHT48K0A3C71NJG8792A
  user_id: null

event_type: state_changed
data:
  entity_id: light.ikea_jetstrom_6060_light
  old_state:
    entity_id: light.ikea_jetstrom_6060_light
    state: "on"
    attributes:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 176
      color_temp_kelvin: 3322
      color_temp: 301
      hs_color:
        - 27.369
        - 48.786
      rgb_color:
        - 255
        - 187
        - 131
      xy_color:
        - 0.467
        - 0.377
      off_with_transition: false
      off_brightness: null
      friendly_name: IKEA JETSTROM 6060 Light
      supported_features: 40
    last_changed: "2025-11-16T10:26:49.458894+00:00"
    last_reported: "2025-11-16T10:29:18.745233+00:00"
    last_updated: "2025-11-16T10:29:18.745233+00:00"
    context:
      id: 01KA63CGS04PD2XX55VDEGDDWV
      parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
      user_id: null
  new_state:
    entity_id: light.ikea_jetstrom_6060_light
    state: "on"
    attributes:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4000
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 150
      color_temp_kelvin: 3322
      color_temp: 301
      hs_color:
        - 27.369
        - 48.786
      rgb_color:
        - 255
        - 187
        - 131
      xy_color:
        - 0.467
        - 0.377
      off_with_transition: false
      off_brightness: null
      friendly_name: IKEA JETSTROM 6060 Light
      supported_features: 40
    last_changed: "2025-11-16T10:26:49.458894+00:00"
    last_reported: "2025-11-16T10:29:19.338974+00:00"
    last_updated: "2025-11-16T10:29:19.338974+00:00"
    context:
      id: 01KA63CGS04PD2XX55VDEGDDWV
      parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:19.338974+00:00"
context:
  id: 01KA63CGS04PD2XX55VDEGDDWV
  parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
  user_id: null

event_type: state_changed
data:
  entity_id: automation.hook_light
  old_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T10:29:17.743261+00:00"
      mode: restart
      current: 1
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T10:29:17.743392+00:00"
    last_updated: "2025-11-16T10:29:17.743392+00:00"
    context:
      id: 01KA63CGS04PD2XX55VDEGDDWV
      parent_id: 01KA63CG942K5V5RNR13Z1PCQ9
      user_id: null
  new_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T10:29:17.743261+00:00"
      mode: restart
      current: 2
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T10:29:19.347004+00:00"
    last_updated: "2025-11-16T10:29:19.347004+00:00"
    context:
      id: 01KA63CJAKKEFFHA622AFC3BW1
      parent_id: 01KA63CHTFB42QF5YVEM01RF6N
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:19.347004+00:00"
context:
  id: 01KA63CJAKKEFFHA622AFC3BW1
  parent_id: 01KA63CHTFB42QF5YVEM01RF6N
  user_id: null

event_type: state_changed
data:
  entity_id: automation.hook_light
  old_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T10:29:17.743261+00:00"
      mode: restart
      current: 2
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T10:29:19.347004+00:00"
    last_updated: "2025-11-16T10:29:19.347004+00:00"
    context:
      id: 01KA63CJAKKEFFHA622AFC3BW1
      parent_id: 01KA63CHTFB42QF5YVEM01RF6N
      user_id: null
  new_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T10:29:17.743261+00:00"
      mode: restart
      current: 1
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T10:29:19.357637+00:00"
    last_updated: "2025-11-16T10:29:19.357637+00:00"
    context:
      id: 01KA63CJAKKEFFHA622AFC3BW1
      parent_id: 01KA63CHTFB42QF5YVEM01RF6N
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:19.357637+00:00"
context:
  id: 01KA63CJAKKEFFHA622AFC3BW1
  parent_id: 01KA63CHTFB42QF5YVEM01RF6N
  user_id: null

event_type: automation_triggered
data:
  name: Hook - Light
  entity_id: automation.hook_light
  source: event 'ahb_controller_event'
origin: LOCAL
time_fired: "2025-11-16T10:29:19.365884+00:00"
context:
  id: 01KA63CJAKKEFFHA622AFC3BW1
  parent_id: 01KA63CHTFB42QF5YVEM01RF6N
  user_id: null

event_type: state_changed
data:
  entity_id: automation.hook_light
  old_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T10:29:17.743261+00:00"
      mode: restart
      current: 1
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T10:29:19.357637+00:00"
    last_updated: "2025-11-16T10:29:19.357637+00:00"
    context:
      id: 01KA63CJAKKEFFHA622AFC3BW1
      parent_id: 01KA63CHTFB42QF5YVEM01RF6N
      user_id: null
  new_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T10:29:19.366143+00:00"
      mode: restart
      current: 1
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T10:29:19.366243+00:00"
    last_updated: "2025-11-16T10:29:19.366243+00:00"
    context:
      id: 01KA63CJAKKEFFHA622AFC3BW1
      parent_id: 01KA63CHTFB42QF5YVEM01RF6N
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:19.366243+00:00"
context:
  id: 01KA63CJAKKEFFHA622AFC3BW1
  parent_id: 01KA63CHTFB42QF5YVEM01RF6N
  user_id: null

event_type: state_changed
data:
  entity_id: automation.hook_light
  old_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T10:29:19.366143+00:00"
      mode: restart
      current: 1
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T10:29:19.366243+00:00"
    last_updated: "2025-11-16T10:29:19.366243+00:00"
    context:
      id: 01KA63CJAKKEFFHA622AFC3BW1
      parent_id: 01KA63CHTFB42QF5YVEM01RF6N
      user_id: null
  new_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T10:29:19.366143+00:00"
      mode: restart
      current: 0
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T10:29:19.398370+00:00"
    last_updated: "2025-11-16T10:29:19.398370+00:00"
    context:
      id: 01KA63CJAKKEFFHA622AFC3BW1
      parent_id: 01KA63CHTFB42QF5YVEM01RF6N
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T10:29:19.398370+00:00"
context:
  id: 01KA63CJAKKEFFHA622AFC3BW1
  parent_id: 01KA63CHTFB42QF5YVEM01RF6N
  user_id: null
```
</details>

Hopefully, I haven't exposed anything important...

**Comment by yarafie** [comment]
> > Since you are using ZHA, Can you send me the exact events that are triggered when you do a long press up and long press down and also the events when you release each.
> 
> Yep there's definitely something going on. The up button long press doesn't fire almost anything compared to the down button...
> 
> UP BUTTON LONG PRESS (held for at least 5 seconds)
> DOWN BUTTON LONG PRESS

@Seminko 

This was extremly helpful.

Re-Download the blueprint again, and I'm 99% sure I fixed the Up Button Long/Release.

https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2001_e2002

**Comment by Seminko** [comment]
@yarafie up long press fixed! Nice

Left and right long press doesn't work for me still, but it probably doesn't matter because there are only 5 checkpoints. But... Even short presses don't work reliably...

Would the event logs help?

**Comment by yarafie** [comment]
> @yarafie up long press fixed! Nice
> 
> Left and right long press doesn't work for me still, but it probably doesn't matter because there are only 5 checkpoints. But... Even short presses don't work reliably...
> 
> Would the event logs help?

Yes. :)

**Comment by Seminko** [comment]
@yarafie 

<details>
  <summary>LEFT BUTTON LONG PRESS - didn't do anything</summary>

```
event_type: zha_event
data:
  device_ieee: f8:44:77:ff:fe:75:e2:65
  device_id: 46e870a32d42baac192e18bfc429d3a9
  unique_id: f8:44:77:ff:fe:75:e2:65:1:0x0005
  endpoint_id: 1
  cluster_id: 5
  command: release
  args:
    - 0
  params:
    param1: 0
origin: LOCAL
time_fired: "2025-11-16T12:49:09.335303+00:00"
context:
  id: 01KA6BCKPQ488YVA92S77T2EYB
  parent_id: null
  user_id: null

event_type: automation_triggered
data:
  name: Controller - IKEA E2001/E2002 STYRBAR Remote control
  entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
  source: event 'zha_event'
origin: LOCAL
time_fired: "2025-11-16T12:49:09.366601+00:00"
context:
  id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  parent_id: 01KA6BCKPQ488YVA92S77T2EYB
  user_id: null

event_type: state_changed
data:
  entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
  old_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1763292807057"
      last_triggered: "2025-11-16T12:48:59.324256+00:00"
      mode: restart
      current: 0
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T11:33:32.011195+00:00"
    last_reported: "2025-11-16T12:48:59.398445+00:00"
    last_updated: "2025-11-16T12:48:59.398445+00:00"
    context:
      id: 01KA6BC9XBE5WXPSNHQQ84DQ0Q
      parent_id: 01KA6BC9WYVE7DT4F6SRR0FV0Q
      user_id: null
  new_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1763292807057"
      last_triggered: "2025-11-16T12:49:09.367036+00:00"
      mode: restart
      current: 1
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T11:33:32.011195+00:00"
    last_reported: "2025-11-16T12:49:09.367213+00:00"
    last_updated: "2025-11-16T12:49:09.367213+00:00"
    context:
      id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
      parent_id: 01KA6BCKPQ488YVA92S77T2EYB
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T12:49:09.367213+00:00"
context:
  id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  parent_id: 01KA6BCKPQ488YVA92S77T2EYB
  user_id: null

event_type: call_service
data:
  domain: input_text
  service: set_value
  service_data:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    value:
      a: button-arrows-release
      t: 1763297349.385419
origin: LOCAL
time_fired: "2025-11-16T12:49:09.387028+00:00"
context:
  id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  parent_id: 01KA6BCKPQ488YVA92S77T2EYB
  user_id: null

event_type: state_changed
data:
  entity_id: input_text.ikea_jetstrom_blueprint_helper
  old_state:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    state: "{\"a\":\"button-left-short\",\"t\":1763297339.345311}"
    attributes:
      editable: true
      min: 0
      max: 100
      pattern: null
      mode: text
      icon: mdi:ceiling-light
      friendly_name: IKEA Jetström blueprint helper
    last_changed: "2025-11-16T12:48:59.349060+00:00"
    last_reported: "2025-11-16T12:48:59.349060+00:00"
    last_updated: "2025-11-16T12:48:59.349060+00:00"
    context:
      id: 01KA6BC9XBE5WXPSNHQQ84DQ0Q
      parent_id: 01KA6BC9WYVE7DT4F6SRR0FV0Q
      user_id: null
  new_state:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    state: "{\"a\":\"button-arrows-release\",\"t\":1763297349.385419}"
    attributes:
      editable: true
      min: 0
      max: 100
      pattern: null
      mode: text
      icon: mdi:ceiling-light
      friendly_name: IKEA Jetström blueprint helper
    last_changed: "2025-11-16T12:49:09.388006+00:00"
    last_reported: "2025-11-16T12:49:09.388006+00:00"
    last_updated: "2025-11-16T12:49:09.388006+00:00"
    context:
      id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
      parent_id: 01KA6BCKPQ488YVA92S77T2EYB
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T12:49:09.388006+00:00"
context:
  id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  parent_id: 01KA6BCKPQ488YVA92S77T2EYB
  user_id: null

event_type: ahb_controller_event
data:
  controller: 46e870a32d42baac192e18bfc429d3a9
  action: button_right_release
origin: LOCAL
time_fired: "2025-11-16T12:49:09.435550+00:00"
context:
  id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  parent_id: 01KA6BCKPQ488YVA92S77T2EYB
  user_id: null

event_type: call_service
data:
  domain: input_text
  service: set_value
  service_data:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    value:
      a: button-arrows-release
      t: 1763297349.440066
origin: LOCAL
time_fired: "2025-11-16T12:49:09.440984+00:00"
context:
  id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  parent_id: 01KA6BCKPQ488YVA92S77T2EYB
  user_id: null

event_type: state_changed
data:
  entity_id: input_text.ikea_jetstrom_blueprint_helper
  old_state:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    state: "{\"a\":\"button-arrows-release\",\"t\":1763297349.385419}"
    attributes:
      editable: true
      min: 0
      max: 100
      pattern: null
      mode: text
      icon: mdi:ceiling-light
      friendly_name: IKEA Jetström blueprint helper
    last_changed: "2025-11-16T12:49:09.388006+00:00"
    last_reported: "2025-11-16T12:49:09.388006+00:00"
    last_updated: "2025-11-16T12:49:09.388006+00:00"
    context:
      id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
      parent_id: 01KA6BCKPQ488YVA92S77T2EYB
      user_id: null
  new_state:
    entity_id: input_text.ikea_jetstrom_blueprint_helper
    state: "{\"a\":\"button-arrows-release\",\"t\":1763297349.440066}"
    attributes:
      editable: true
      min: 0
      max: 100
      pattern: null
      mode: text
      icon: mdi:ceiling-light
      friendly_name: IKEA Jetström blueprint helper
    last_changed: "2025-11-16T12:49:09.443387+00:00"
    last_reported: "2025-11-16T12:49:09.443387+00:00"
    last_updated: "2025-11-16T12:49:09.443387+00:00"
    context:
      id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
      parent_id: 01KA6BCKPQ488YVA92S77T2EYB
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T12:49:09.443387+00:00"
context:
  id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  parent_id: 01KA6BCKPQ488YVA92S77T2EYB
  user_id: null

event_type: state_changed
data:
  entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
  old_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1763292807057"
      last_triggered: "2025-11-16T12:49:09.367036+00:00"
      mode: restart
      current: 1
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T11:33:32.011195+00:00"
    last_reported: "2025-11-16T12:49:09.367213+00:00"
    last_updated: "2025-11-16T12:49:09.367213+00:00"
    context:
      id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
      parent_id: 01KA6BCKPQ488YVA92S77T2EYB
      user_id: null
  new_state:
    entity_id: automation.controller_ikea_e2001_e2002_styrbar_remote_control
    state: "on"
    attributes:
      id: "1763292807057"
      last_triggered: "2025-11-16T12:49:09.367036+00:00"
      mode: restart
      current: 0
      friendly_name: Controller - IKEA E2001/E2002 STYRBAR Remote control
    last_changed: "2025-11-16T11:33:32.011195+00:00"
    last_reported: "2025-11-16T12:49:09.445123+00:00"
    last_updated: "2025-11-16T12:49:09.445123+00:00"
    context:
      id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
      parent_id: 01KA6BCKPQ488YVA92S77T2EYB
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T12:49:09.445123+00:00"
context:
  id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  parent_id: 01KA6BCKPQ488YVA92S77T2EYB
  user_id: null

event_type: automation_triggered
data:
  name: Hook - Light
  entity_id: automation.hook_light
  source: event 'ahb_controller_event'
origin: LOCAL
time_fired: "2025-11-16T12:49:09.458432+00:00"
context:
  id: 01KA6BCKT6BYHWND466D3SN9DE
  parent_id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  user_id: null

event_type: state_changed
data:
  entity_id: automation.hook_light
  old_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T12:48:59.413453+00:00"
      mode: restart
      current: 0
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T12:48:59.744795+00:00"
    last_updated: "2025-11-16T12:48:59.744795+00:00"
    context:
      id: 01KA6BCA08QCYPFPFSFD886T16
      parent_id: 01KA6BC9XBE5WXPSNHQQ84DQ0Q
      user_id: null
  new_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T12:49:09.458681+00:00"
      mode: restart
      current: 1
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T12:49:09.458783+00:00"
    last_updated: "2025-11-16T12:49:09.458783+00:00"
    context:
      id: 01KA6BCKT6BYHWND466D3SN9DE
      parent_id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T12:49:09.458783+00:00"
context:
  id: 01KA6BCKT6BYHWND466D3SN9DE
  parent_id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  user_id: null

event_type: state_changed
data:
  entity_id: automation.hook_light
  old_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T12:49:09.458681+00:00"
      mode: restart
      current: 1
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T12:49:09.458783+00:00"
    last_updated: "2025-11-16T12:49:09.458783+00:00"
    context:
      id: 01KA6BCKT6BYHWND466D3SN9DE
      parent_id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
      user_id: null
  new_state:
    entity_id: automation.hook_light
    state: "on"
    attributes:
      id: "1762285350768"
      last_triggered: "2025-11-16T12:49:09.458681+00:00"
      mode: restart
      current: 0
      friendly_name: Hook - Light
    last_changed: "2025-11-04T19:42:39.208948+00:00"
    last_reported: "2025-11-16T12:49:09.497778+00:00"
    last_updated: "2025-11-16T12:49:09.497778+00:00"
    context:
      id: 01KA6BCKT6BYHWND466D3SN9DE
      parent_id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
      user_id: null
origin: LOCAL
time_fired: "2025-11-16T12:49:09.497778+00:00"
context:
  id: 01KA6BCKT6BYHWND466D3SN9DE
  parent_id: 01KA6BCKQ5KF6HX17ZVDCPXZ6E
  user_id: null
```
</details>

**Comment by yarafie** [comment]
> [@yarafie](https://github.com/yarafie)
> 
> LEFT BUTTON LONG PRESS - didn't do anything

Can you re-download the blueprint again and try.

When you press either the right or left arrow buttons, don't release immediatly, but wait a few seconds, I found that for me the long press actions don't take affect immediatly.

If Right/Left Long Press then release still don't work can you do the following.

1. Disable the associated light hook automation temporarily
2. Press the Right Arrow Button, **"COUNT TO 15 SLOWLY"** then release the Right Arrow button.
3. Post the trace log for it here.
4. Repeat steps 2 and 3 for the Left Arrow Button
5. You can enable the associated light hook automation again so at least your automations will work kind of until I get a chance to look through the 2 trace logs.

**Comment by Seminko** [comment]
> When you press either the right or left arrow buttons, don't release immediatly, but wait a few seconds, I found that for me the long press actions don't take affect immediatly.

Yea, I do hold it pressed pretty long. I held it down just a second for the logs sake, so I don't have to copy dozens of logs ;)

The left and right long press work now but quite unreliably. Sometimes it works immediately, sometimes it takes like 5 seconds to work, sometimes doesn't work even after 10s. Same with short presses.

But for it's good enough for me now, so thanks!

**Comment by yarafie** [comment]
@Seminko 

I believe I just fixed the left/right long hold/release issue.

Can you give it a final try.

https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2001_e2002

**Comment by Seminko** [comment]
@yarafie I don't see a difference. There is still much more lag / delay before the long press is recognized on the left / right buttons compared to up / down. Up / down are snappy, responsive.

**Comment by yarafie** [comment]
> [@yarafie](https://github.com/yarafie) I don't see a difference. There is still much more lag / delay before the long press is recognized on the left / right buttons compared to up / down. Up / down are snappy, responsive.

This is a problem with the ikea styrbar itself. The right/left arrows don't register a long push immediatly. You can test it yourself by listening to ZHA events for your styrbar and you will see that, at least for me  using zigbee2mqtt, I have to count to 4 or 5 seconds before the action from the stybar for a long push is registered. Nothing much I can do about that in the blueprint itself.

The question does the long press actions work and the corresponding release stops the action.

I was testing it with an IKEA TRADFRI bulb E26/E27, white spectrum, globe, opal, 1000 lm (LED1732G11) and I was able to change the hue frim white to yellow and back by using the right/left long presses, so I confirmed that at least for me it works.

**Comment by Seminko** [comment]
Gotcha, hence this is the best we could do at the moment. Thanks!

**Comment by Los7** [comment]
I had the same issue with ZHA. Yarafie's version fixed it also for me:
https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2001_e2002/EPMatt/ikea_e2001_e2002
Unfortunately the fix is not yet on the main repo.
Thanks for the work and for fixing this!
